//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by object_viewer.rc
//
#define IDR_MAINFRAME                   1
#define IDEMPTY                         3
#define IDI_MAIN_ICO                    101
#define IDD_SLOT                        1000
#define IDD_MAIN_DLG                    1001
#define IDC_SCROLLBAR1                  1002
#define IDD_ANIMATION_SET               1002
#define IDC_SCROLLBAR                   1002
#define IDC_RED_AMOUNT                  1002
#define IDC_PSI_SCROLLBAR               1002
#define IDC_SLOT_NAME                   1003
#define IDD_SELECT_STRING               1003
#define IDC_GREEN_AMOUNT                1003
#define IDC_THETA_SCROLLBAR             1003
#define IDD_ANIMATION                   1004
#define IDC_BLUE_AMOUNT                 1004
#define IDC_PHI_SCROLLBAR               1004
#define IDC_BLEND                       1005
#define IDD_SCENE                       1005
#define IDC_ALPHA_AMOUNT                1005
#define IDD_PARTICLE                    1006
#define IDC_DOOMY_BLEND                 1007
#define IDD_EDITABLE_RANGE              1007
#define IDC_START_BLEND                 1008
#define IDD_LOCATED_PROPERTIES          1008
#define IDC_START_BLEND_SPIN            1009
#define IDB_PARTICLE_SYSTEM             1009
#define IDC_END_BLEND                   1010
#define IDB_LOCATED                     1010
#define IDC_END_BLEND_SPIN              1011
#define IDB_PARTICLE                    1011
#define IDC_START_TIME                  1012
#define IDB_EMITTER                     1012
#define IDC_START_TIME_SPIN             1013
#define IDB_FORCE                       1013
#define IDC_END_TIME                    1014
#define IDB_COLLISION_ZONE              1014
#define IDC_END_TIME_SPIN               1015
#define IDB_LIGHT                       1015
#define IDC_SPEED_FACTOR                1016
#define IDD_SELECT_RANGE                1016
#define IDC_SPEED_FACTOR_SPIN           1017
#define IDR_PARTICLE_MENU               1017
#define IDR_LOCATED_MENU                1017
#define IDC_SMOOTHNESS                  1018
#define IDR_MENU1                       1018
#define IDC_SMOOTHNESS_SPIN             1019
#define IDD_PARTICLE_SYSTEM_START_STOP  1019
#define IDC_SET_ANIMATION               1020
#define IDB_START_SYSTEM                1020
#define IDC_SET_SKELETON                1021
#define IDC_TREE                        1021
#define IDB_STOP_SYSTEM                 1021
#define IDC_ADD_ANIMATION               1022
#define IDC_ALIGN_BLEND                 1022
#define IDD_SIZEDPARTICLE               1022
#define IDD_ATTRIB_DLG                  1022
#define IDC_RESET                       1023
#define IDC_LIST                        1023
#define IDC_OFFSET                      1023
#define IDC_TREE2                       1024
#define IDC_OFFSET_SPIN                 1024
#define IDR_MENU2                       1024
#define IDC_ADD_SKEL_WT                 1025
#define IDC_TIME_LINE                   1025
#define IDR_LOCATED_BINDABLE_MENU       1025
#define IDC_FRW                         1026
#define IDR_PARTICLE_SYSTEM_MENU        1026
#define IDC_LIST_INSERT                 1026
#define IDC_FFW                         1027
#define IDD_LOCATED_BINDABLE            1027
#define IDC_LIST_DELETE                 1027
#define IDB_PARTICLE_SIZE               1028
#define IDC_LIST_UP                     1028
#define IDC_START                       1029
#define IDB_PARTICLE_COLOR              1029
#define IDC_LIST_DOWN                   1029
#define IDC_END                         1030
#define IDB_PARTICLE_ANGLE              1030
#define IDC_SET_ANIM_LENGTH             1030
#define IDC_START_EDIT                  1031
#define IDD_COLOR_EDIT                  1031
#define IDC_END_EDIT                    1032
#define IDC_CLAMP                       1032
#define IDC_REPEAT                      1033
#define IDD_VALUE_BLENDER               1033
#define IDC_DISABLE                     1034
#define IDD_GRADIENT_DLG                1034
#define IDC_CURRENT_FRAME               1035
#define IDC_INVERT_SKELETON_WEIGHT      1035
#define IDD_EMITTER_DIALOG              1035
#define IDC_SPEED                       1036
#define IDC_LOAD_MESH                   1036
#define IDC_ENABLE                      1036
#define IDC_LOAD_PLAYLIST               1037
#define IDB_EMISSION_QUANTITY           1037
#define IDC_CLEAR_SCENE                 1038
#define IDB_EMISSION_PERIOD             1038
#define IDC_SAVE_PLAYLIST               1039
#define IDB_MODULATE_STRENGHT           1039
#define IDC_LOAD_SCENE                  1040
#define IDD_TEXTURE_CHOOSER             1040
#define IDC_VIEW_ANIMATION              1041
#define IDD_LOCATED_TARGET_DLG          1041
#define IDC_VIEW_ANIMATIONSET           1042
#define IDC_STOP                        1042
#define IDB_LOCATED_INSTANCE            1042
#define IDC_VIEW_SLOTS                  1043
#define IDC_PLAY                        1043
#define IDD_PS_MOVER                    1043
#define IDC_LOOP                        1044
#define IDC_RESET_CAMERA                1044
#define IDD_BASIS_EDIT                  1044
#define IDC_EULER                       1045
#define IDC_OBJECT_MODE                 1046
#define IDB_BASIS                       1046
#define IDC_MOVE_SPEED                  1047
#define IDD_HINT_ROTATE_THE_SAME        1047
#define IDC_VIEW_PARTICLE               1048
#define IDD_TAIL_PARTICLE               1048
#define IDC_SLIDER                      1050
#define IDC_MOVE_ELEMENT                1050
#define IDD_CHOOSE_MESH                 1050
#define IDC_SELECT_RANGE                1051
#define IDD_DIRECTION_ATTR              1051
#define IDC_MAX_RANGE                   1052
#define IDD_DIRECTION_EDIT              1052
#define IDC_UPDATE_VALUE                1053
#define IDD_ZONE                        1053
#define IDC_VALUE                       1054
#define IDC_LIMITED_LIFE_TIME           1054
#define IDC_MIN_RANGE                   1055
#define IDC_CHECK2                      1055
#define IDC_SYSTEM_BASIS                1055
#define IDC_TAIL_PERSIST_AFTER_DEATH    1055
#define IDR_MOVE_ELEMENT                1055
#define IDC_ACCURATE_INTEGRATION        1055
#define IDC_DISPLAY_INTERPOLATION       1055
#define IDC_BORDERS_ONLY                1055
#define IDC_CHECK_VEGETABLE_MESH        1055
#define IDR_LOCATED_INSTANCE_MENU       1056
#define IDC_CHECK_VEGETABLE_BENDPHASE   1056
#define IDC_LIFE_MIN_VALUE              1057
#define IDD_TEXTURE_ANIM                1057
#define IDC_CHECK_VEGETABLE_SCALEXY     1057
#define IDC_LIFE_MAX_VALUE              1058
#define IDB_ANIM_SEQUENCE               1058
#define IDC_PARTICLE_NUMBER_POS         1059
#define IDD_SCHEME_EDIT                 1059
#define IDD_MEMORY_VALUE_DLG            1060
#define IDC_MASS_MIN_VALUE              1061
#define IDB_FORCE_INTENSITY             1061
#define IDC_MASS_MAX_VALUE              1062
#define IDC_LIFETIME_MIN_STATIC         1063
#define IDB_LIFE_TIME                   1063
#define IDC_LOWER_BOUND                 1064
#define IDB_WEIGHT                      1064
#define IDC_UPPER_BOUND                 1065
#define IDR_OBJECT_VIEWER_MENU          1065
#define IDD_EDIT_USER_PARAM             1065
#define IDD_EDIT_PARTICLE_SYSTEM        1067
#define IDD_BIN_OP                      1068
#define IDR_TOOL_EDIT                   1069
#define IDC_COMBO1                      1070
#define IDC_USE_SCHEME                  1070
#define IDC_TYPE_OF_EMISSION            1070
#define IDC_TAIL_SHAPE                  1070
#define IDC_COLLISION_BEHAVIOUR         1070
#define IDC_USER_PARAM_INDEX            1070
#define IDC_BIN_OP                      1070
#define IDC_PS_DIE_ON_EVENT             1070
#define IDC_MAP_SIZE                    1070
#define IDC_COMBO_DIST_TYPE             1070
#define IDC_MAIN_OP                     1070
#define IDC_CURRENT_STAGE               1070
#define IDC_DEGRADATION_EXPONENT        1070
#define IDC_EDITED_OBJECT               1070
#define IDC_START_PICTURE               1071
#define IDD_SET_VALUE                   1071
#define IDC_ALTERNATE_OP                1071
#define IDC_STOP_PICTURE                1072
#define IDC_SCHEME                      1073
#define IDC_EDIT_SCHEME                 1074
#define IDI_APP_ICON                    1074
#define IDB_SOUND                       1075
#define IDC_GET_SCHEME                  1075
#define IDC_CLAMP_ATTRIB                1076
#define IDD_SOUND                       1076
#define IDC_SCHEME_INPUT                1077
#define IDB_SOUND_VOLUME                1077
#define IDC_ATTRIB_NB_CYCLES            1078
#define IDB_SOUND_FREQ                  1078
#define IDD_ABOUT                       1079
#define IDC_PUT_SCHEME                  1079
#define IDD_LB_EXTERN_ID                1080
#define IDC_ATTR_BITMAP                 1081
#define IDD_PICK_SOUND                  1081
#define IDC_CONSTANT_VALUE_POS          1082
#define IDD_CHOOSE_LAG                  1082
#define IDD_EDITSPINNER                 1083
#define IDD_SCHEME_BANK_DLG             1084
#define IDD_CHOOSE_NAME                 1085
#define IDC_AVAILABLE_TARGET            1086
#define IDB_PARTICLE_WIDTH              1086
#define IDC_PARTICLE_COLOR              1087
#define IDB_PARTICLE_HEIGHT             1087
#define IDC_BINDABLE_TYPE               1088
#define IDD_CURVE_EDIT                  1088
#define IDC_BROWSE_COLOR                1089
#define IDD_DAYNIGHT                    1089
#define IDC_VALUE1                      1090
#define IDD_VEGETABLE_DLG               1090
#define IDC_VALUE2                      1091
#define IDD_VEGETABLE_DENSITY_DLG       1091
#define IDC_EDITED_VALUE                1092
#define IDD_CHOOSE_POOL_ID              1092
#define IDC_INSERT_VALUE                1093
#define IDD_VEGETABLE_NOISE_VALUE_DLG   1093
#define IDC_ADD_VALUE                   1094
#define IDC_VALUE_UP                    1095
#define IDD_VEGETABLE_APPEARANCE_DLG    1095
#define IDC_VALUE_DOWN                  1096
#define IDD_VEGETABLE_SCALE_DLG         1096
#define IDC_REMOVE_VALUE                1097
#define IDC_GRADIENT_LIST               1098
#define IDD_VEGETABLE_ROTATE_DLG        1098
#define IDD_VEGETABLE_SELECT_OTHER      1099
#define IDD_VEGETABLE_COPY              1100
#define IDC_EMITTED_TYPE                1101
#define IDD_DIALOG_PROGRESS             1101
#define IDD_VEGETABLE_WIND              1102
#define IDD_MULTITEX                    1103
#define IDC_BROWSE_TEXTURE              1104
#define IDC_REMOVE_TEXTURE              1105
#define IDC_EDIT_MULTITEXTURING         1106
#define IDD_CONSTRAINT_MESH_DLG         1106
#define IDD_CONSTRAINT_MESH_TEX_DLG     1107
#define IDC_USE_SPEED_BASIS             1108
#define IDC_ADD_TARGET                  1109
#define IDD_CONSTRAINT_MESH_GLOBAL_TEX_ANIM_DLG 1109
#define IDC_REMOVE_TARGET               1110
#define IDD_EDIT_MORPH_MESH             1110
#define IDC_TARGET                      1111
#define IDB_MORPH_SCHEME                1111
#define IDC_ENABLE_X                    1112
#define IDD_RIBBON_DLG                  1112
#define IDC_ENABLE_Y                    1113
#define IDC_XPOS                        1113
#define IDD_AUTO_LOD                    1113
#define IDC_ENABLE_Z                    1114
#define IDC_YPOS                        1114
#define IDC_ZPOS                        1115
#define IDC_CURSOR1                     1115
#define IDC_UPDATE_XPOS                 1116
#define IDD_GLOBAL_COLOR                1116
#define IDC_UPDATE_YPOS                 1117
#define IDD_GLOBAL_WIND                 1117
#define IDC_UPDATE_ZPOS                 1118
#define IDC_SUB_COMPONENT               1119
#define IDC_PSI_VALUE                   1121
#define IDC_THETA_VALUE                 1122
#define IDC_HINT_PRECOMPUTED_ROTATIONS  1122
#define IDC_PHI_VALUE                   1123
#define IDC_ROT_SPEED_MIN               1123
#define IDC_UPDATE_MIN_ROT_SPEED        1124
#define IDC_ROT_SPEED_MAX               1125
#define IDC_TAIL_FADE                   1125
#define IDC_UPDATE_MAX_ROT_SPEED        1126
#define IDC_TAIL_IN_SYSTEM_BASIS        1126
#define IDC_BROWSE_SHAPE                1126
#define IDC_NB_MODELS                   1127
#define IDC_SHAPE_NAME                  1127
#define IDC_UPDATE_NB_MODELS            1128
#define IDC_VECT_I                      1128
#define IDC_VECT_MINUS_I                1129
#define IDC_VECT_J                      1130
#define IDC_VECT_MINUS_J                1131
#define IDC_CUSTOM_DIRECTION            1132
#define IDC_VECT_K                      1134
#define IDC_VECT_MINUS_K                1135
#define IDC_ENABLE_TEXTURE_ANIM         1139
#define IDC_CHOOSE_TEXTURES             1140
#define IDC_NO_SAMPLES                  1141
#define IDC_BLENDING_MODE               1142
#define IDC_BLENDING_MODE_STATIC        1143
#define IDC_BG_COLOR                    1144
#define IDC_EDIT_INPUT                  1147
#define IDC_ENABLE_SLOW_DOWN            1148
#define IDC_FORCE_LIFE_TIME_UPDATE      1149
#define IDC_DISPLAY_BBOX                1152
#define IDC_BB_X                        1153
#define IDC_BB_Y                        1154
#define IDC_BB_Z                        1155
#define IDC_UPDATE_BBOX                 1156
#define IDC_PRECOMPUTE_BBOX             1157
#define IDC_INC_BBOX                    1158
#define IDC_SOUND_NAME                  1158
#define IDC_DEC_BBOX                    1159
#define IDC_BROWSE_SOUND                1159
#define IDC_DIE_WHEN_OUT_OF_RANGE       1160
#define IDC_APPLY_AFTRE_DELAY           1161
#define IDC_DIE_WHEN_OUT_OF_FRUSTRUM    1162
#define IDC_DISGRADE_WITH_LOD           1163
#define IDC_PERFORM_MOTION_WHEN_OUT_OF_FRUSTUM 1163
#define IDC_VERSION                     1164
#define IDC_ENABLE_EXTERN_ID            1165
#define IDC_ID_VALUE                    1166
#define IDC_LIST1                       1168
#define IDC_SPAWN                       1169
#define IDC_BUTTON1                     1170
#define IDC_MUTE                        1171
#define IDC_PLAY_SOUND                  1171
#define IDC_ZOOM_IN                     1171
#define IDC_DELETE_POOL                 1171
#define IDC_BUTTON_VEGETABLE_INSERT     1171
#define IDC_BUTTON_VEGETABLE_GENERAL_NONE 1171
#define IDC_UPDATE_SPEED_ALTERNATE      1171
#define IDC_LAG                         1172
#define IDC_GO_UP                       1172
#define IDC_RENAME_POOL                 1172
#define IDC_BUTTON_VEGETABLE_REMOVE     1172
#define IDC_BUTTON_VEGETABLE_APPERANCE_ALL 1172
#define IDC_CHANGE                      1172
#define IDC_CONVERT_SPEED_VECTOR_FROM_EMITTER_BASIS 1173
#define IDC_GO_DOWN                     1173
#define IDC_BUTTON_VEGETABLE_GETOTHER   1173
#define IDC_BUTTON_VEGETABLE_SAVE_SET   1173
#define IDC_BUTTON_VEGETABLE_APPEARANCE_NONE 1173
#define IDC_INSERT                      1173
#define IDC_REMOVE                      1174
#define IDC_CENTER_CURVE                1174
#define IDC_BUTTON_VEGETABLE_SAVE_DESC  1174
#define IDC_BUTTON_VEGETABLE_POSITION_ALL 1174
#define IDC_SCHEME_LIST                 1175
#define IDC_FIRST_EQUAL_LAST            1175
#define IDC_BUTTON_VEGETABLE_POSITION_NONE 1175
#define IDC_UP                          1175
#define IDC_NAME_CHOSEN                 1176
#define IDC_RENAME                      1176
#define IDC_DOWN                        1176
#define IDC_SAVE_BANK                   1177
#define IDC_LOAD_BANK                   1178
#define IDC_INDE_SIZES                  1179
#define IDC_SIZE_WIDTH                  1180
#define IDC_SIZE_HEIGHT                 1181
#define IDC_WIDTH_HEIGHT_BOX            1182
#define IDC_ZOOM_OUT                    1183
#define IDC_ADD_POINT                   1184
#define IDC_REMOVE_POINT                1185
#define IDC_MOVE_POINT                  1186
#define IDC_SMOOTHING_ON                1187
#define IDC_LAST_EQUAL_FIRST            1188
#define IDC_PARAMETRIC_MOTION           1189
#define IDC_TRIGGER_ON_DEATH            1191
#define IDC_EDIT_TRIGGER_ON_DEATH       1192
#define IDC_INPLACE                     1194
#define IDC_INC_POS                     1195
#define IDC_USE_LIST                    1195
#define IDC_USE_MIXER                   1196
#define IDC_PLAYLIST                    1197
#define IDC_SLIDER1                     1198
#define IDC_SLIDER_ANGLE_MIN            1198
#define IDC_SLIDER_VEGETABLE_SCALE_NOISE 1198
#define IDC_SLIDER_VEGETABLE_WIND_POWER 1198
#define IDC_SLIDER_ANGLE_MAX            1199
#define IDC_SLIDER_VEGETABLE_WIND_BENDSTART 1199
#define IDC_LIST_VEGETABLE              1200
#define IDC_SLIDER_VEGETABLE_WIND_FREQUENCY 1200
#define IDC_AUTOMATIC_WAVES_GENERATION  1203
#define IDC_VEGETABLE_NOISE_VALUE_NAME  1204
#define IDC_LOAD_POOL                   1205
#define IDC_SAVE_POOL                   1206
#define IDC_POOL_LIST                   1211
#define IDC_WATER_UNIT_SIZE             1212
#define IDC_DAMPING                     1213
#define IDC_FILTER_WEIGHT               1214
#define IDC_IMPULSION_STRENGHT          1215
#define IDC_PERIOD                      1216
#define IDC_IMPULSION_RADIUS            1217
#define IDC_ADD_POOL                    1218
#define IDC_POOL_ID                     1219
#define IDC_PROPAGATION_TIME            1219
#define IDC_POOL_NAME                   1220
#define IDC_RADIO_ANGLE_FLOOR           1223
#define IDC_RADIO_ANGLE_WALL            1224
#define IDC_RADIO_ANGLE_CEILING         1225
#define IDC_EDIT_ANGLE_MIN              1226
#define IDC_EDIT_ANGLE_MAX              1227
#define IDC_CHECK_MAX_DENSITY           1228
#define IDC_STATIC_MAX_DENSITY          1229
#define IDC_STATIC_SELECT_VEGETABLE     1230
#define IDC_BUTTON_VEGETABLE_BROWSE     1233
#define IDC_LIST_VEGETABLE_COLOR        1237
#define IDC_BUTTON_VEGETABLE_ADD        1238
#define IDC_STATIC_VEGETABLE_SCALE      1239
#define IDC_STATIC_VEGETABLE_SHAPENAME  1240
#define IDC_BUTTON_VEGETABLE_APPEND_SET 1241
#define IDC_BUTTON_VEGETABLE_LOAD_DESC  1242
#define IDC_BUTTON_VEGETABLE_CLEAR      1243
#define IDC_BUTTON_VEGETABLE_LOAD_SET   1244
#define IDC_BUTTON_VEGETABLE_COPY       1245
#define IDC_CHECK_VEGETABLE_SUBSET_COPY 1246
#define IDC_CHECK_VEGETABLE_DISTANCE    1247
#define IDC_CHECK_VEGETABLE_MAXDENSITY  1248
#define IDC_CHECK_VEGETABLE_DENSITY     1249
#define IDC_CHECK_VEGETABLE_ANGLESETUP  1250
#define IDC_CHECK_VEGETABLE_BENDFACTOR  1251
#define IDC_CHECK_VEGETABLE_COLORSETUP  1252
#define IDC_CHECK_VEGETABLE_COLORNOISE  1253
#define IDC_BUTTON_VEGETABLE_GENERAL_ALL 1254
#define IDC_CHECK_VEGETABLE_SCALEZ      1255
#define IDC_BUTTON_VEGETABLE_REFRESH    1255
#define IDC_CHECK_VEGETABLE_ROTATEY     1256
#define IDC_CHECK_VEGETABLE_ROTATEX     1257
#define IDC_CHECK_VEGETABLE_SHOW        1257
#define IDC_CHECK_VEGETABLE_ROTATEZ     1258
#define IDC_PROGRESS1                   1258
#define IDC_CHECK_VEGETABLE_AUTOMATIC   1258
#define IDC_STATIC_PROGRESS_DESC        1259
#define IDC_BUTTON_VEGETABLE_SETUP_WIND 1260
#define IDC_STATIC_VEGETABLE_WIND_POWER 1261
#define IDC_STATIC_VEGETABLE_WIND_BENDSTART 1262
#define IDC_STATIC_VEGETABLE_WIND_FREQUENCY 1263
#define IDC_BUTTON_CLOSE                1264
#define IDC_CHECK_VEGETABLE_SNAPTOGROUND 1265
#define IDC_CHECK_VEGETABLE_ENABLE      1266
#define IDC_STATIC_VEGETABLE_PERF       1267
#define IDC_U_SPEED_1                   1269
#define IDC_V_SPEED_1                   1270
#define IDC_U_SPEED_2                   1271
#define IDC_V_SPEED_2                   1272
#define IDS_U_SPEED_1                   1273
#define IDS_V_SPEED_1                   1274
#define IDS_U_SPEED_2                   1275
#define IDS_V_SPEED_2                   1276
#define IDC_TEX_CHOOSER                 1277
#define IDC_U_SPEED_1_ALTERNATE         1278
#define IDC_V_SPEED_1_ALTERNATE         1279
#define IDC_U_SPEED_2_ALTERNATE         1280
#define IDC_V_SPEED_2_ALTERNATE         1281
#define IDS_U_SPEED_1_ALTERNATE         1282
#define IDS_V_SPEED_1_ALTERNATE         1283
#define IDS_U_SPEED_2_ALTERNATE         1284
#define IDS_V_SPEED_2_ALTERNATE         1285
#define IDC_TEX_CHOOSER_ALTERNATE       1286
#define IDC_UPDATE_SPEED                1287
#define IDC_EDIT_MULTITEX               1288
#define IDC_ENABLE_ALTERNATE_TEX        1289
#define IDC_ENABLE_MULTITEXTURING       1290
#define IDC_MULTITEX                    1291
#define IDC_MULTITEX_BORDER             1292
#define IDC_FORCE_BASIC_CAPS            1293
#define IDC_USE_PARTICLE_DATE2          1294
#define IDC_USE_PARTICLE_DATE           1295
#define IDC_FORCE_STAGE_0_MODULATION    1295
#define IDC_FORCE_STAGE_1_MODULATION    1296
#define IDC_FORCE_STAGE_2_MODULATION    1297
#define IDC_FORCE_STAGE_3_MODULATION    1298
#define IDC_FORCE_VERTEX_COLOR_LIGHTING 1299
#define IDC_U_SPEED_TEXT                1300
#define IDC_V_SPEED_TEXT                1301
#define IDC_U_ACCEL_TEXT                1302
#define IDC_V_ACCEL_TEXT                1303
#define IDC_U_SPEED                     1304
#define IDC_CURR_STAGE                  1305
#define IDC_V_SPEED                     1305
#define IDC_TEX_ANIM_TYPE_TEXT          1306
#define IDC_U_ACCEL                     1306
#define IDC_TEX_ANIM_TYPE               1307
#define IDC_V_ACCEL                     1307
#define IDC_U_SCALE_SPEED_TEXT          1308
#define IDC_REINIT_WHEN_NEW_ELEMENT_IS_CREATED 1308
#define IDC_V_SCALE_SPEED_TEXT          1309
#define IDC_ENABLE_MORPHING             1309
#define IDC_U_SCALE_ACCEL_TEXT          1310
#define IDC_EDIT_MORPH                  1310
#define IDC_V_SCALE_ACCEL_TEXT          1311
#define IDC_MORPH_FRAME                 1311
#define IDC_U_SCALE_SPEED               1312
#define IDC_MESHS                       1312
#define IDC_V_SCALE_SPEED               1313
#define IDC_ADD                         1313
#define IDC_U_SCALE_ACCEL               1314
#define IDC_MORPH_SCHEME                1314
#define IDC_V_SCALE_ACCEL               1315
#define IDC_DELAYED_EMISSION            1315
#define IDC_U_SCALE_START_TEXT          1316
#define IDC_MAX_EMISSION_COUNT          1316
#define IDC_V_SCALE_START_TEXT          1317
#define IDC_SPEED_INHERITANCE_FACTOR_FRAME 1317
#define IDC_U_SCALE_START               1318
#define IDC_DELAYED_EMISSION_FRAME      1318
#define IDC_RED_EDIT                    1318
#define IDC_V_SCALE_START               1319
#define IDC_MAX_EMISSION_COUNT_FRAME    1319
#define IDC_BLUE_EDIT                   1319
#define IDC_USE_HERMITTE_INTERPOLATION  1319
#define IDC_WROT_SPEED_TEXT             1320
#define IDC_GREEN_EDIT                  1320
#define IDC_CONSTANT_LENGTH             1320
#define IDC_WROT_ACCEL_TEXT             1321
#define IDC_ALPHA_EDIT                  1321
#define IDC_RIBBON_LENGTH               1321
#define IDC_WROT_SPEED                  1322
#define IDC_LOD_DEGRADATION             1322
#define IDC_ANIM_TYPE                   1322
#define IDC_WROT_ACCEL                  1323
#define IDC_ANIM_TYPE_CTRL              1323
#define IDC_LIFE_MGT_PRESETS            1324
#define IDC_SHARABLE                    1325
#define IDC_ENABLE_AUTO_LOD             1326
#define IDC_EDIT_AUTO_LOD               1327
#define IDC_START_PERCENT_DIST          1328
#define IDC_NO_AUTO_LOD                 1329
#define IDC_GLOBAL_COLOR                1330
#define IDC_EDIT_GLOBAL_COLOR           1331
#define IDC_COLOR_ATTRIB                1332
#define IDC_INPUT_MULTIPLIER_TXT        1333
#define IDC_SRC_INPUT_TXT               1334
#define IDC_SKIP_PARTICLES              1335
#define IDC_BUMP_FACTOR_TXT             1337
#define IDC_BUMP_FACTOR                 1338
#define IDC_CONSISTENT_EMISSION         1340
#define IDC_SLIDER_GLOBAL_WIND_POWER    1341
#define IDC_STATIC_GLOBAL_WIND_POWER    1342
#define IDM_DOT_LOC                     2000
#define IDM_LOOKAT_LOC                  2001
#define IDM_FANLIGHT_LOC                2002
#define IDM_RIBBON_LOC                  2003
#define IDM_TAILDOT_LOC                 2004
#define IDM_MESH_LOC                    2005
#define IDM_CONSTRAINT_MESH_LOC         2006
#define IDM_FACE_LOC                    2007
#define IDM_SHOCKWAVE_LOC               2008
#define IDM_GRAVITY_FORCE_LOC           2009
#define IDM_DIRECTIONNAL_FORCE_LOC      2010
#define IDM_SPRING_FORCE_LOC            2011
#define IDM_FLUID_FRICTION_LOC          2012
#define IDM_CENTRAL_GRAVITY_LOC         2013
#define IDM_CYLINDRIC_VORTEX_LOC        2014
#define IDM_BROWNIAN_MOVE_LOC           2015
#define IDM_ZONE_PLANE_LOC              2016
#define IDM_ZONE_SPHERE_LOC             2017
#define IDM_ZONE_RECTANGLE_LOC          2018
#define IDM_ZONE_DISC_LOC               2019
#define IDM_ZONE_CYLINDER_LOC           2020
#define IDM_DIRECTIONNAL_EMITTER_LOC    2021
#define IDM_OMNIDIRECTIONNAL_EMITTER_LOC 2022
#define IDM_RECTANGLE_EMITTER_LOC       2023
#define IDM_CONIC_EMITTER_LOC           2024
#define IDM_SPHERICAL_EMITTER_LOC       2025
#define IDM_SOUND_LOC                   2026
#define IDD_WATER_POOL                  3666
#define IDM_DOT                         32773
#define IDM_LOOKAT                      32774
#define IDM_FANLIGHT                    32775
#define IDM_RIBBON                      32776
#define IDM_TAILDOT                     32777
#define IDM_MESH                        32778
#define IDM_CONSTRAINT_MESH             32779
#define IDM_FACE                        32780
#define IDM_DIRECTIONNAL_EMITTER        32781
#define IDM_OMNIDIRECTIONNAL_EMITTER    32782
#define IDM_RECTANGLE_EMITTER           32783
#define IDM_CONIC_EMITTER               32784
#define IDM_GRAVITY_FORCE               32786
#define IDM_SPRING_FORCE                32787
#define IDM_ZONE_PLANE                  32788
#define IDM_ZONE_SPHERE                 32789
#define IDM_ZONE_RECTANGLE              32790
#define IDM_ZONE_DISC                   32791
#define IDM_ZONE_CYLINDER               32792
#define IDM_DELETE_PARTICLE             32793
#define IDM_DELETE_LOCATED              32793
#define ID_ESSAI1_ESSAI2                32797
#define ID_A_ESSAI                      32798
#define ID_BINDPARTICLE_PONT            32800
#define ID__A                           32801
#define ID__B                           32802
#define ID_MENU_DELETE                  32803
#define ID_MENU_DELETE_PS               32803
#define ID_MENU_NEWLOCATED              32804
#define IDM_DELETE_LOCATED_BINDABLE     32806
#define ID_INSTANCIATE_LOCATED          32807
#define ID_MENU_SAVE_PS                 32808
#define ID_MENU_LOAD_PS                 32809
#define ID_ENABLE_ELEMENT_XROTATE       32810
#define ID_ENABLE_ELEMENT_YROTATE       32811
#define ID_ENABLE_ELEMENT_ZROTATE       32812
#define IDM_SHOCKWAVE                   32813
#define IDM_DELETE_LOCATED_INSTANCE     32814
#define IDM_RESET_ROTATION              32815
#define IDM_FLUID_FRICTION              32816
#define IDM_CYLINDRIC_VORTEX            32818
#define IDM_SPHERICAL_EMITTER           32819
#define IDM_DIRECTIONNAL_FORCE          32820
#define IDM_CENTRAL_GRAVITY             32821
#define IDM_BROWNIAN_MOVE               32822
#define IDM_LB_LOD1N2                   32823
#define ID_FILE_EXIT                    32824
#define IDM_LB_LOD1                     32824
#define ID_CLEAR                        32825
#define IDM_LB_LOD2                     32825
#define ID_FILE_LOADCONFIG              32826
#define ID_FILE_SAVECONFIG              32827
#define ID_VIEW_SETBACKGROUND           32828
#define ID_VIEW_RESET_CAMERA            32829
#define ID_VIEW_OBJECTMODE              32830
#define ID_VIEW_FIRSTPERSONMODE         32831
#define ID_VIEW_SETMOVESPEED            32832
#define ID_WINDOW_ANIMATIONSET          32836
#define ID_WINDOW_MIXERSSLOTS           32837
#define ID_WINDOW_PARTICLES             32838
#define ID_EDIT_MOVEELEMENT             32839
#define ID_EDIT_X                       32840
#define ID_EDIT_Y                       32841
#define ID_EDIT_Z                       32842
#define ID_WINDOW_ANIMATION             32845
#define ID_BUTTON32846                  32846
#define ID_BUTTON32847                  32847
#define ID_BUTTON32848                  32848
#define ID_BUTTON32849                  32849
#define ID_BUTTON32852                  32852
#define IDM_SOUND                       32857
#define ID_HELP_ABOUTOBJECTVIEWER       32858
#define IDM_LB_EXTERN_ID                32859
#define ID_FILE_BINDSCENEANIMATION      32861
#define IDM_SET_LAG                     32862
#define IDM_REMOVE_ALL_INSTANCES_FROM_SCENE 32863
#define IDM_MERGE_PS                    32864
#define IDM_RIBBON_LOOK_AT              32865
#define IDM_RIBBON_LOOK_AT_LOC          32866
#define IDM_MAGNETIC_FORCE              32867
#define IDM_MAGNETIC_FORCE_LOC          32868
#define IDM_RADIAL_EMITTER              32869
#define IDM_RADIAL_EMITTER_LOC          32870
#define ID_WINDOW_DAYNIGHT              32871
#define ID_WINDOW_VEGETABLE             32872
#define ID_WINDOW_WATER_POOL            32873
#define IDM_ACTIVATE_TEXTURE_SET_1      32875
#define IDM_ACTIVATE_TEXTURE_SET_4      32876
#define IDM_ACTIVATE_TEXTURE_SET_2      32877
#define IDM_ACTIVATE_TEXTURE_SET_3      32878
#define IDM_ACTIVATE_TEXTURE_SET_5      32879
#define IDM_ACTIVATE_TEXTURE_SET_6      32880
#define IDM_ACTIVATE_TEXTURE_SET_7      32881
#define IDM_ACTIVATE_TEXTURE_SET_8      32882
#define ID_WINDOW_GLOBALWIND            32883

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1118
#define _APS_NEXT_COMMAND_VALUE         32884
#define _APS_NEXT_CONTROL_VALUE         1343
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
