#! /bin/sh

set -x

rm -f config.cache

# This is to avoid atomake to complain about the fact that there is no
# ChangeLog File at the moment
if  test ! -f ChangeLog
then
	touch ChangeLog
fi

libtoolize --force --copy
&& aclocal \
&& autoheader \
&& automake --gnu --add-missing --copy \
&& autoconf
