#! /bin/sh

set -x

rm -f config.cache

# This is to avoid atomake to complain about the fact that there is no
# ChangeLog or README file at the moment
if test ! -f ChangeLog
then
	touch ChangeLog
fi

if test ! -f README
then
	touch README
fi

aclocal \
&& autoheader \
&& automake --gnu --add-missing --copy \
&& autoconf

